### ISSUE TITLE
Understanding method_subrelations?

### ISSUE THREAD

**Issue by ymohit** [allenai/SciREX#11]
Just a quick question about the format. Why is the number of spans in method_subrelations are not matching umber of spans in coref.

First example: 04320b6d3e6e50a5faf0e54ae2b8b8739445a026

    doc['method_subrelations'] {'Transformer_LRPE_PE_Re-ranking_Ensemble': [[[0, 11], 'Transformer'], [[12, 16], 'LRPE'], [[17, 19], 'PE'], [[20, 30], 'Re-ranking'], [[31, 39], 'Ensemble']]} = 39
    len(doc['json_dict']['coref']['Transformer_LRPE_PE_Re-ranking_Ensemble']) = 34

Second example: '060ff1aad5619a7d6d6cdfaf8be5da29bff3808c'

    len(doc['json_dict']['coref']['LISA___ELMo']) == 16
    doc['words'][5959:5961] = ['ELMo', 'models'] -- this is the 2nd last mention.
    doc['method_subrelations'] {'LISA': [[[0, 4], 'LISA']], 'LISA___ELMo': [[[0, 4], 'LISA'], [[7, 11], 'ELMo']]} = 11

Am I misinterpreting or missing something?

**Comment by successar** [comment]
Hi Mohit, the spans in this are not coref spans : for example , in doc['method_subrelations'] {'Transformer_LRPE_PE_Re-ranking_Ensemble': [[[0, 11], 'Transformer'], [[12, 16], 'LRPE'], [[17, 19], 'PE'], [[20, 30], 'Re-ranking'], [[31, 39], 'Ensemble']]} "

When I write [0, 11], 'Transformer' , it means characters 0-11 in string '`Transformer`_`LRPE`_`PE`_`Re-ranking`_`Ensemble`' and so on. They have nothing to do with coref where each of these subspans are mapped to actual mentions in the document

**Comment by ymohit** [comment]
Got it. Thanks for clarifying.
