### ISSUE TITLE
Issue with predicting relations end-to-end

### ISSUE THREAD

**Issue by viswavi** [allenai/SciREX#14]
When I try predicting relations end-to-end in the `predict_scirex_model.sh` script (after resolving the issues in #12 and #13), I am getting another error:
```FileNotFoundError: [Errno 2] No such file or directory: 'outputs/pwc_outputs/experiment_scirex_full/everything//metrics.json'```

I'm not sure when this `everything` directory could have been constructed in the code, since such a directory name is not hardcoded in the training code, nor did the instructions ask to set it as an environmental variable. 
Might this be a typo?

**Comment by successar** [comment]
I have updated the prediction script. Can you let me know if it works now ?

**Comment by viswavi** [comment]
Yeah that seems to work now - error went away
